/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:52b127bc-ecc6-4ee3-b18c-c4acdef9882a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_GUFAtwkrN",
    "aws_user_pools_web_client_id": "594mnqdmakesv8o2gdqke4i7vk",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsExports;
